const accessories = [
  {
    id: 7,
    category: 'accessories',
    title: 'Сумка"Kolesa Team"',
    price: 700,
    isNew: true,
    img: '../src/assets/img/products/bag-big.jpg',
    fileName: 'bag-big',
    details: 'Брендированная сумка от Qazaq Republic"',
  },
  {
    id: 8,
    category: 'accessories',
    title: 'Носки "Kolesa Team Plus"',
    price: 180,
    isNew: false,
    img: '../src/assets/img/products/socks-big.jpg',
    fileName: 'socks-big',
    details: 'Брендированные носки "Kolesa Team"',
  },
  {
    id: 9,
    category: 'accessories',
    title: 'Бутылка для воды "Kolesa Team"',
    price: 600,
    isNew: false,
    img: '../src/assets/img/products/bottle-big.jpg',
    fileName: 'bottle-big',
    details: 'Бутылка для воды с трубочкой, очень удобная и эргономичная',
  },
  {
    id: 10,
    category: 'accessories',
    title: 'Носки "Kolesa Team"',
    price: 150,
    isNew: false,
    img: '../src/assets/img/products/socks-big.jpg',
    fileName: 'socks-big',
    details: 'Брендированные носки "Kolesa Team"',
  },
  {
    id: 11,
    category: 'accessories',
    title: 'Бутылка для воды "Kolesa Team"',
    price: 600,
    isNew: true,
    img: '../src/assets/img/products/bottle-big.jpg',
    fileName: 'bottle-big',
    details: 'Бутылка для воды с трубочкой, очень удобная и эргономичная',
  },
  {
    id: 12,
    category: 'accessories',
    title: 'Сумка"Kolesa Team"',
    price: 600,
    isNew: false,
    img: '../src/assets/img/products/bag-big.jpg',
    fileName: 'bag-big',
    details: 'Брендированная сумка от Qazaq Republic"',
  },
];

export default accessories;
