const clothes = [
  {
    id: 1,
    category: 'clothes',
    title: 'Футболка "Эволюционируй или сдохни"',
    price: 220,
    isNew: false,
    img: '../src/assets/img/products/t-shirt-img.jpg',
    fileName: 't-shirt-img',
    details: 'Брендированная футболка от Qazaq Republic',
  },
  {
    id: 2,
    category: 'clothes',
    title: 'Футболка "Almaty"',
    price: 220,
    isNew: false,
    img: '../src/assets/img/products/t-shirt-almaty.jpg',
    fileName: 't-shirt-almaty',
    details: 'Брендированный свитшот "Almaty"',
  },
  {
    id: 3,
    category: 'clothes',
    title: 'Свитшот "Kolesa Team Premium"',
    price: 400,
    isNew: true,
    img: '../src/assets/img/products/hoody-blue-big.jpg',
    fileName: 'hoody-blue-big',
    details: 'Брендированный свитшот "Kolesa Team"',
  },
  {
    id: 4,
    category: 'clothes',
    title: 'Футболка "Эволюционируй или умри"',
    price: 220,
    isNew: true,
    img: '../src/assets/img/products/t-shirt-img.jpg',
    fileName: 't-shirt-img',
    details: 'Брендированная футболка от Qazaq Republic',
  },

  {
    id: 5,
    category: 'clothes',
    title: 'Свитшот "Kolesa Team"',
    price: 300,
    isNew: false,
    img: '../src/assets/img/products/hoody-blue-big.jpg',
    fileName: 'hoody-blue-big',
    details: 'Брендированный свитшот "Kolesa Team"',
  },
  {
    id: 6,
    category: 'clothes',
    title: 'Футболка "Almaty"',
    price: 350,
    isNew: false,
    img: '../src/assets/img/products/t-shirt-almaty.jpg',
    fileName: 't-shirt-almaty',
    details: 'Брендированный свитшот "Almaty"',
  },
];

export default clothes;
